#!/bin/bash
rosbag record --split --size=4096 -b 1024 -o $1 \
/tf_static \
/tf \
/rosout \
/rosout_agg \
/rosout \
/move_base/current_goal \
/move_base/goal \
/move_base/recovery_status \
/move_base_simple/goal \
/move_base/current_goal \
/move_base/local_costmap/costmap \
/move_base/global_costmap/costmap \
/twist_auto \
/Odometry \
/ouster/points \
/camera/aligned_depth_to_color/camera_info \
/camera/aligned_depth_to_color/image_raw/compressed \
/camera/color/image_raw/compressed \
/zed2i/zed_node/left/image_rect_color/compressed \
/zed2i/zed_node/left/camera_info \
/zed2i/zed_node/depth/depth_registered/compressed \
/zed2i/zed_node/left/image_rect_raw \
/zed2i/zed_node/imu/data \
/zed2i/zed_node/imu/data_raw \
/grounding_dino_ros/debug \
/grounding_dino_ros/detections \
/grounding_dino_ros/detections_viz \
/tracker_node/viz \
/tracker_node/detections_viz \
/llm_planning_node/graph_viz \
/llm_planning_node/graph \
/llm_planning_node/filtered_costmap \
/grounding_dino_ros/pred \
/ublox/fix \
/imu/imu \
/imu/magnetic_field \
/jackal_teleop/is_auto  \
/ddb/client_sm_state/basestation \
/ddb/client_sm_state/io \
/ddb/client_sm_state/titan \
/ddb/client_stats/basestation \
/ddb/client_stats/io \
/ddb/client_stats/titan \
/ddb/client_sync_complete/basestation \
/ddb/client_sync_complete/io \
/ddb/client_sync_complete/titan \
/ddb/rajant/log \
/ddb/rajant/rssi/basestation \
/ddb/rajant/rssi/io \
/ddb/rajant/rssi/titan \
/ddb/server_sync_complete/basestation \
/ddb/server_sync_complete/io \
/ddb/server_sync_complete/titan \
/ddb/topic_publisher/headers
